#!/bin/sh
####################
# run some tests on APRS packet generation
####################

MYCALL="N0CALL-11"
# Desired -
# ZULU_DDHHMM="091024"
ZULU_DDHHMM=`date "+%d%H%M"`
LAT_DDMMxSS="3449.27"
LAT_NS="N"
LON_DDDMMxSS="11740.79"
LON_WE="W"
MSG="Warpig-III balloon"
ALT="003285"


rm -f z.txt
#rm -f 1.txt 2.txt 3.txt 4.txt 5.txt 6.txt 7.txt z.txt

#  echo "N0CALL-11>APNXXX:@080749z3449.27N/11740.79W$" >> z.txt
#  echo "N0CALL-11>APNXXX,WIDE1-1:@080749z3449.27N/11740.79W$" >> z.txt
#  echo "N0CALL-11>APNXXX:/080749z3449.27N/11740.79W>Warpig-III balloon/A=003285" >> z.txt
#  echo "N0CALL-11>APNXXX,WIDE1-1:/080749z3449.27N/11740.79W>Warpig-III balloon/A=003285" >> z.txt
#  echo "N0CALL-11>APNXXX,WIDE2-2:/080749z3449.27N/11740.79W>Warpig-III balloon/A=003285" >> z.txt
#  echo "N0CALL-11>BEACON:@080749z3449.27N/11740.79W$" >> z.txt
#  echo "N0CALL-11>BEACON,WIDE1-1:@080749z3449.27N/11740.79W$" >> z.txt
#  echo "N0CALL-11>WIDE1-1,BEACON:@080749z3449.27N/11740.79W$" >> z.txt
#  echo "N0CALL-11>BEACON:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285" >> z.txt
#  echo "N0CALL-11>BEACON,WIDE1-1:/080749z3449.27N/11740.79W>Warpig-III balloon/A=003285" >> z.txt
#  echo "N0CALL-11>BEACON,WIDE2-2:/080749z3449.27N/11740.79W>Warpig-III balloon/A=003285" >> z.txt
#  echo "N0CALL-11>BEACON,WIDE3-3:/080749z3449.27N/11740.79W>Warpig-III balloon/A=003285" >> z.txt
#  echo "N0CALL-11>APDW12:#Test packet" >> z.txt
#
# gen_packets -o z.wav z.txt
#
# atest z.wav
#
# echo
# echo "To play the file you just built, do this - "
# echo "pifm z.wav 144.394157 44100 mono 4"
# echo


echo "${MYCALL}>APNXXX:#First test packet" >> z.txt

## THE FOLLOWING WORKED, GREAT! -
echo "${MYCALL}>APNXXX:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt
echo "${MYCALL}>APNXXX,WIDE1-1:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt
echo "${MYCALL}>APNXXX,WIDE2-2:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt
echo "${MYCALL}>BEACON:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt
echo "${MYCALL}>BEACON,WIDE2-2:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt
echo "${MYCALL}>BEACON,WIDE3-3:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt
echo "${MYCALL}>BEACON,WIDE1-1:/${ZULU_DDHHMM}z${LAT_DDMMxSS}${LAT_NS}/${LON_DDDMMxSS}${LON_WE}O${MSG}/A=${ALT}" >> z.txt

## FOR SOME REASON, the last packet does not seem to send properly, so put one or two more with "gibberish" to flush the others
echo "${MYCALL}>APNXXX:#Next-to-last test packet" >> z.txt
echo "${MYCALL}>APNXXX:#Last test packet" >> z.txt

#for A in 1 2 3 4 5 6 7
for A in z
do
    gen_packets -o ${A}.wav ${A}.txt
    atest ${A}.wav

    echo
    echo "To play the file you just built, do this - "
    echo "pifm ${A}.wav 144.394157 44100 mono 4"
    echo
    echo
done

echo

exit 0


#########################################################
#########################################################
THIS IS WHAT Direwolf on Linux (Yaesu FT-857D with Signalink soundcard) thinks -
#########################################################

N0CALL-2 audio level = 7(4/2)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX:@080749z3449.27N/11740.79W$
Position with time, original primary Phone, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE1-1:@080749z3449.27N/11740.79W$
Position with time, original primary Phone, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 7(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX,WIDE1-1:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX,WIDE2-2:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON:@080749z3449.27N/11740.79W$
Position with time, original primary Phone
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>BEACON,WIDE1-1:@080749z3449.27N/11740.79W$
Position with time, original primary Phone
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>WIDE1-1,BEACON:@080749z3449.27N/11740.79W$
Position with time, original primary Phone
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>BEACON:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE1-1:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE2-2:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

=========================================================

N0CALL-2 audio level = 7(4/1)   [NONE]   ____||||:
[0.6] N0CALL-2>APNXXX:@080749z3449.27NS11740.79W>
Position with time, Solar powered, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 7(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE1-1:@080749z3449.27NS11740.79W>
Position with time, Solar powered, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX:/080749z3449.27NS11740.79W>Warpig-II balloon/A=003285
Position with time, Solar powered, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX,WIDE1-1:/080749z3449.27NS11740.79W>Warpig-II balloon/A=003285
Position with time, Solar powered, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX,WIDE2-2:/080749z3449.27NS11740.79W>Warpig-II balloon/A=003285
Position with time, Solar powered, TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON:@080749z3449.27NS11740.79W>
Position with time, Solar powered
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE1-1:@080749z3449.27NS11740.79W>
Position with time, Solar powered
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>WIDE1-1,BEACON:@080749z3449.27NS11740.79W>
Position with time, Solar powered
N 34 49.2700, W 117 40.7900

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON:/080749z3449.27NS11740.79W>Warpig-II balloon/A=003285
Position with time, Solar powered
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE1-1:/080749z3449.27NS11740.79W>Warpig-II balloon/A=003285
Position with time, Solar powered
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

========================================================

N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE2-2:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>BEACON:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon




N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE2-2:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>BEACON:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon


# WAS GOOD -
N0CALL-2>APNXXX:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
N0CALL-2>APNXXX:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285

N0CALL-2>APNXXX,WIDE1-1:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
N0CALL-2>APNXXX,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285

N0CALL-2>APNXXX,WIDE2-2:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
N0CALL-2>APNXXX,WIDE2-2:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285

N0CALL-2>BEACON:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
N0CALL-2>BEACON:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285

N0CALL-2>BEACON,WIDE1-1:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
N0CALL-2>BEACON,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285

N0CALL-2>BEACON,WIDE2-2:/080749z3449.27N/11740.79W>Warpig-II balloon/A=003285
### MISSING THIS ONE!! ###





N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE2-2:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>BEACON:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>BEACON,WIDE1-1:/090059z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon





N0CALL-2 audio level = 7(4/1)   [NONE]   _____||||
[0.6] N0CALL-2>APNXXX:/090738z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE1-1:/090738z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>APNXXX,WIDE2-2:/090738z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view), TNC-X  (K6DBG)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon

N0CALL-2 audio level = 8(4/1)   [NONE]   ______|||
[0.7] N0CALL-2>BEACON:/090738z3449.27N/11740.79W>Warpig-II balloon/A=003285
Position with time, normal car (side view)
N 34 49.2700, W 117 40.7900, alt 3285 ft
Warpig-II balloon


