#!/bin/sh
###########################################
# getmsgacks - Find all messages contained in Direwolf log (either direwolf.log or
#              kiss.log) that were ALREADY ACKNOWLEDGED.
#
# HISTORICAL INFORMATION -
#
#   2019-05-02  msipin  Created
###########################################

# Use whichever one we finally settle on
#LOGFILE=/home/direwolf/direwolf.log
LOGFILE=/home/direwolf/kiss.log
#LOGFILE=/home/direwolf/sccs/direwolf.log

egrep "^\[.*N0CALL.*>.*:ack[0-9].*[0-9]$|^N0CALL.*>.*:ack[0-9].*[0-9]$" ${LOGFILE} | awk -F"::" '{ if (NF >= 2) print $2 }' | awk '{ printf "%s%s\n",$1,$2 }' | sed "s/:ack/:/" | sort -u

exit 0

