#!/bin/sh
##########################################
# getnextseq - Get the next sequence number, and remember we got it
#
# HISTORICAL INFORMATION -
#
#  2019-05-02  msipin  Created
##########################################

SEQFILE=/usr/local/bin/.SEQ_NUM

CURR=`cat ${SEQFILE}`
NEW=`expr $CURR + 1`
echo $NEW > ${SEQFILE}
cat ${SEQFILE}

exit 0

